# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker build'
    command: 'login'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker build'
    repository: 'selvacent / javadocker'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
  
- task: Docker@2
  inputs:
    containerRegistry: 'Docker build'
    command: 'logout'